@startuml

skinparam monochrome true
autonumber

database API_Server
collections VPC_Operator
collections Divider_Operator
collections Network_Operator
collections Bouncer_Operator
collections Endpoints_Operator
collections Droplet_Operator

VPC_Operator -> API_Server: Create a Divider
==Divider Created==
rnote over API_Server: ==Divider Status: Init

Divider_Operator --> API_Server: Sees Divider Status Init
Divider_Operator -> Droplet_Operator: Place Divider
Droplet_Operator -> Droplet_Operator: Places Divider on a Droplet
Droplet_Operator -> Bouncer_Operator: On Divider Placed
group For All Bouncers
Bouncer_Operator -> Bouncer_Operator: Updates Bouncers with Divider info
Bouncer_Operator -> Bouncer_Operator: Updates divider with Bouncer info
end
Bouncer_Operator -> API_Server: Updates status to Provisioned
rnote over API_Server: ==Divider Status: Provisioned
Divider_Operator --> API_Server: Sees status Provisioned
Divider_Operator -> Divider_Operator: Update cache
==Divider Ready==
@enduml
