@startuml

' SPDX-License-Identifier: MIT
' Copyright (c) 2020 The Authors.

' Authors: Sherif Abdelwahab <@zasherif>
'          Phu Tran          <@phudtran>

' Permission is hereby granted, free of charge, to any person obtaining a copy
' of this software and associated documentation files (the "Software"), to deal
' in the Software without restriction, including without limitation the rights
' to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
' copies of the Software, and to permit persons to whom the Software is
' furnished to do so, subject to the following conditions:The above copyright
' notice and this permission notice shall be included in all copies or
' substantial portions of the Software.THE SOFTWARE IS PROVIDED "AS IS",
' WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
' NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
' FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
' TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
' THE USE OR OTHER DEALINGS IN THE SOFTWARE.

skinparam monochrome true
autonumber

database API_Server
database CNI_Service
collections Droplet_Operator

CNI_Service -> API_Server: Create a droplet for each Node
rnote over API_Server: ==Droplet Status: Init
Droplet_Operator -> API_Server: Sees that a droplet has been created
Droplet_Operator -> Droplet_Operator: Update cache with Droplet
Droplet_Operator -> API_Server: Updates droplet status to Provisioned
rnote over API_Server: Droplet Status: Provisioned
Droplet_Operator --> API_Server: See Droplet status Provisioned
Droplet_Operator -> Droplet_Operator: Updates cache

@enduml
