@startuml

' SPDX-License-Identifier: MIT
' Copyright (c) 2020 The Authors.

' Authors: Sherif Abdelwahab <@zasherif>
'          Phu Tran          <@phudtran>

' Permission is hereby granted, free of charge, to any person obtaining a copy
' of this software and associated documentation files (the "Software"), to deal
' in the Software without restriction, including without limitation the rights
' to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
' copies of the Software, and to permit persons to whom the Software is
' furnished to do so, subject to the following conditions:The above copyright
' notice and this permission notice shall be included in all copies or
' substantial portions of the Software.THE SOFTWARE IS PROVIDED "AS IS",
' WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
' NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
' FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
' TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
' THE USE OR OTHER DEALINGS IN THE SOFTWARE.

skinparam monochrome true
skinparam group 10

autonumber
database API_Server
collections CNI_Service
collections VPC_Operator
collections Network_Operator
collections Divider_Operator

==VPC Delete Requested==
VPC_Operator --> API_Server: Sees VPC Delete requested
group For All Networks
VPC_Operator -> Network_Operator: Delete Network

rnote over API_Server: ==Network Deleted
end
Network_Operator ->  Divider_Operator: On all Networks Deleted
group For All Dividers
Divider_Operator -> API_Server: Deletes Divider Object
rnote over API_Server: ==Divider Deleted
Divider_Operator -> Divider_Operator: Update cache
end
Divider_Operator -> VPC_Operator: On all Divider Deleted
VPC_Operator -> API_Server: Deletes VPC Object
rnote over API_Server: ==VPC Deleted
VPC_Operator -> VPC_Operator: Update cache
==VPC Deleted==
@enduml
