@startuml

' SPDX-License-Identifier: MIT
' Copyright (c) 2020 The Authors.

' Authors: Sherif Abdelwahab <@zasherif>
'          Phu Tran          <@phudtran>

' Permission is hereby granted, free of charge, to any person obtaining a copy
' of this software and associated documentation files (the "Software"), to deal
' in the Software without restriction, including without limitation the rights
' to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
' copies of the Software, and to permit persons to whom the Software is
' furnished to do so, subject to the following conditions:The above copyright
' notice and this permission notice shall be included in all copies or
' substantial portions of the Software.THE SOFTWARE IS PROVIDED "AS IS",
' WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
' NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
' FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
' TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
' THE USE OR OTHER DEALINGS IN THE SOFTWARE.
skinparam monochrome true
autonumber

database API_Server
collections Divider_Operator
collections Network_Operator
collections Bouncer_Operator

==Network Delete Requested==
Network_Operator --> API_Server: Sees network delete request
group For All Endpoints
Network_Operator -> Network_Operator: Delete all Endpoints
rnote over API_Server: ==Endpoint Deleted
end
Network_Operator -> Divider_Operator: On All Endpoints Deleted
group For All Bouncers
group For All Dividers
Divider_Operator -> Divider_Operator: Delete Divider information from Bouncer
Divider_Operator --> Divider_Operator: Delete Bouncer information from the Divider
end
Divider_Operator --> Bouncer_Operator: On Bouncer Deprovisioned
Bouncer_Operator -> API_Server: Delete Bouncer Object
rnote over API_Server: ==Bouncer Deleted
Bouncer_Operator -> Bouncer_Operator: Update cache
end
Bouncer_Operator -> Network_Operator: On All Bouncers Deleted
Network_Operator -> API_Server: Deletes Network Object
rnote over API_Server: ==Network Deleted
Network_Operator -> Network_Operator: Update cache.
==Network Deleted==
@enduml
