@startuml

skinparam monochrome true
skinparam group 10

autonumber
database API_Server
collections CNI_Service
collections VPC_Operator
collections Network_Operator
collections Divider_Operator

==VPC Delete Requested==
VPC_Operator --> API_Server: Sees VPC Delete requested
group For All Networks
VPC_Operator -> Network_Operator: Delete Network

rnote over API_Server: ==Network Deleted
end
Network_Operator ->  Divider_Operator: On all Networks Deleted
group For All Dividers
Divider_Operator -> API_Server: Deletes Divider Object
rnote over API_Server: ==Divider Deleted
Divider_Operator -> Divider_Operator: Update cache
end
Divider_Operator -> VPC_Operator: On all Divider Deleted
VPC_Operator -> API_Server: Deletes VPC Object
rnote over API_Server: ==VPC Deleted
VPC_Operator -> VPC_Operator: Update cache
==VPC Deleted==
@enduml
