@startuml

skinparam monochrome true
autonumber

database API_Server
collections Divider_Operator
collections Bouncer_Operator
collections Endpoints_Operator

==Bouncer Delete Requested==
Bouncer_Operator --> API_Server: Sees Bouncer Delete Request
Bouncer_Operator -> Endpoints_Operator: Remove Bouncer info from endpoints and vice versa.
group For All Endpoints
Endpoints_Operator -> Endpoints_Operator: Delete Bouncer info Endpoints
Endpoints_Operator -> Endpoints_Operator: Delete Endpoint info from Bouncer host
end
Endpoints_Operator -> Divider_Operator: On Bouncer-EndpointDelete
group For All Dividers
Divider_Operator -> Divider_Operator: Delete  Bouncer info from Divider
Divider_Operator -> Divider_Operator: Delete Divider info from Bouncer host
end
Divider_Operator -> Bouncer_Operator: On Bouncer Deprovisioned
Bouncer_Operator -> API_Server: Deletes Bouncer Object
rnote over API_Server: == Bouncer Deleted
Bouncer_Operator -> Bouncer_Operator: Updates cache
==Bouncer Deleted==
@enduml
