@startuml

skinparam monochrome true
autonumber

database API_Server
collections Divider_Operator
collections Network_Operator
collections Bouncer_Operator

==Network Delete Requested==
Network_Operator --> API_Server: Sees network delete request
group For All Endpoints
Network_Operator -> Network_Operator: Delete all Endpoints
rnote over API_Server: ==Endpoint Deleted
end
Network_Operator -> Divider_Operator: On All Endpoints Deleted
group For All Bouncers
group For All Dividers
Divider_Operator -> Divider_Operator: Delete Divider information from Bouncer
Divider_Operator --> Divider_Operator: Delete Bouncer information from the Divider
end
Divider_Operator --> Bouncer_Operator: On Bouncer Deprovisioned
Bouncer_Operator -> API_Server: Delete Bouncer Object
rnote over API_Server: ==Bouncer Deleted
Bouncer_Operator -> Bouncer_Operator: Update cache
end
Bouncer_Operator -> Network_Operator: On All Bouncers Deleted
Network_Operator -> API_Server: Deletes Network Object
rnote over API_Server: ==Network Deleted
Network_Operator -> Network_Operator: Update cache.
==Network Deleted==
@enduml
