# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from mizar.proto import interface_pb2 as mizar_dot_proto_dot_interface__pb2


class InterfaceServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeInterfaces = channel.unary_unary(
                '/mizar.InterfaceService/InitializeInterfaces',
                request_serializer=mizar_dot_proto_dot_interface__pb2.InterfacesList.SerializeToString,
                response_deserializer=mizar_dot_proto_dot_interface__pb2.InterfacesList.FromString,
                )
        self.ProduceInterfaces = channel.unary_unary(
                '/mizar.InterfaceService/ProduceInterfaces',
                request_serializer=mizar_dot_proto_dot_interface__pb2.InterfacesList.SerializeToString,
                response_deserializer=mizar_dot_proto_dot_interface__pb2.InterfacesList.FromString,
                )
        self.ConsumeInterfaces = channel.unary_unary(
                '/mizar.InterfaceService/ConsumeInterfaces',
                request_serializer=mizar_dot_proto_dot_interface__pb2.CniParameters.SerializeToString,
                response_deserializer=mizar_dot_proto_dot_interface__pb2.InterfacesList.FromString,
                )
        self.DeleteInterface = channel.unary_unary(
                '/mizar.InterfaceService/DeleteInterface',
                request_serializer=mizar_dot_proto_dot_interface__pb2.InterfaceId.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class InterfaceServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def InitializeInterfaces(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProduceInterfaces(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsumeInterfaces(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInterface(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InterfaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeInterfaces': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeInterfaces,
                    request_deserializer=mizar_dot_proto_dot_interface__pb2.InterfacesList.FromString,
                    response_serializer=mizar_dot_proto_dot_interface__pb2.InterfacesList.SerializeToString,
            ),
            'ProduceInterfaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ProduceInterfaces,
                    request_deserializer=mizar_dot_proto_dot_interface__pb2.InterfacesList.FromString,
                    response_serializer=mizar_dot_proto_dot_interface__pb2.InterfacesList.SerializeToString,
            ),
            'ConsumeInterfaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsumeInterfaces,
                    request_deserializer=mizar_dot_proto_dot_interface__pb2.CniParameters.FromString,
                    response_serializer=mizar_dot_proto_dot_interface__pb2.InterfacesList.SerializeToString,
            ),
            'DeleteInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInterface,
                    request_deserializer=mizar_dot_proto_dot_interface__pb2.InterfaceId.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mizar.InterfaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InterfaceService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def InitializeInterfaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mizar.InterfaceService/InitializeInterfaces',
            mizar_dot_proto_dot_interface__pb2.InterfacesList.SerializeToString,
            mizar_dot_proto_dot_interface__pb2.InterfacesList.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProduceInterfaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mizar.InterfaceService/ProduceInterfaces',
            mizar_dot_proto_dot_interface__pb2.InterfacesList.SerializeToString,
            mizar_dot_proto_dot_interface__pb2.InterfacesList.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConsumeInterfaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mizar.InterfaceService/ConsumeInterfaces',
            mizar_dot_proto_dot_interface__pb2.CniParameters.SerializeToString,
            mizar_dot_proto_dot_interface__pb2.InterfacesList.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mizar.InterfaceService/DeleteInterface',
            mizar_dot_proto_dot_interface__pb2.InterfaceId.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
