// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.1
// source: droplets/droplets.proto

package droplets

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// requests
type Droplet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac            string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Ip             string `protobuf:"bytes,2,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Status         string `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Interface      string `protobuf:"bytes,4,opt,name=Interface,proto3" json:"Interface,omitempty"`
	CreateTime     string `protobuf:"bytes,5,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	ProvisionDelay string `protobuf:"bytes,6,opt,name=ProvisionDelay,proto3" json:"ProvisionDelay,omitempty"`
}

func (x *Droplet) Reset() {
	*x = Droplet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_droplets_droplets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Droplet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Droplet) ProtoMessage() {}

func (x *Droplet) ProtoReflect() protoreflect.Message {
	mi := &file_droplets_droplets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Droplet.ProtoReflect.Descriptor instead.
func (*Droplet) Descriptor() ([]byte, []int) {
	return file_droplets_droplets_proto_rawDescGZIP(), []int{0}
}

func (x *Droplet) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *Droplet) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Droplet) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Droplet) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Droplet) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Droplet) GetProvisionDelay() string {
	if x != nil {
		return x.ProvisionDelay
	}
	return ""
}

type DropletId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *DropletId) Reset() {
	*x = DropletId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_droplets_droplets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropletId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropletId) ProtoMessage() {}

func (x *DropletId) ProtoReflect() protoreflect.Message {
	mi := &file_droplets_droplets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropletId.ProtoReflect.Descriptor instead.
func (*DropletId) Descriptor() ([]byte, []int) {
	return file_droplets_droplets_proto_rawDescGZIP(), []int{1}
}

func (x *DropletId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

//response
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_droplets_droplets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_droplets_droplets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_droplets_droplets_proto_rawDescGZIP(), []int{2}
}

type DropletsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsonReturncode string `protobuf:"bytes,1,opt,name=json_returncode,json=jsonReturncode,proto3" json:"json_returncode,omitempty"`
}

func (x *DropletsResponse) Reset() {
	*x = DropletsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_droplets_droplets_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropletsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropletsResponse) ProtoMessage() {}

func (x *DropletsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_droplets_droplets_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropletsResponse.ProtoReflect.Descriptor instead.
func (*DropletsResponse) Descriptor() ([]byte, []int) {
	return file_droplets_droplets_proto_rawDescGZIP(), []int{3}
}

func (x *DropletsResponse) GetJsonReturncode() string {
	if x != nil {
		return x.JsonReturncode
	}
	return ""
}

var File_droplets_droplets_proto protoreflect.FileDescriptor

var file_droplets_droplets_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x73, 0x2f, 0x64, 0x72, 0x6f, 0x70, 0x6c,
	0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x72, 0x6f, 0x70, 0x6c,
	0x65, 0x74, 0x73, 0x22, 0xa9, 0x01, 0x0a, 0x07, 0x44, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61,
	0x63, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x22,
	0x1b, 0x0a, 0x09, 0x44, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x3b, 0x0a, 0x10, 0x44, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x6a, 0x73, 0x6f,
	0x6e, 0x5f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x6a, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x63, 0x6f,
	0x64, 0x65, 0x32, 0xb3, 0x02, 0x0a, 0x0f, 0x44, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x44, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x6c, 0x65,
	0x74, 0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x1a, 0x0f, 0x2e, 0x64, 0x72, 0x6f,
	0x70, 0x6c, 0x65, 0x74, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x35, 0x0a,
	0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x12, 0x11,
	0x2e, 0x64, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x6c, 0x65,
	0x74, 0x1a, 0x0f, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x73, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x44, 0x72, 0x6f, 0x70,
	0x6c, 0x65, 0x74, 0x12, 0x13, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x73, 0x2e, 0x44,
	0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x1a, 0x1a, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x6c,
	0x65, 0x74, 0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x12, 0x13, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x6c, 0x65,
	0x74, 0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x1a, 0x0f, 0x2e, 0x64,
	0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x37, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x44, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74,
	0x12, 0x13, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x73, 0x2e, 0x44, 0x72, 0x6f, 0x70,
	0x6c, 0x65, 0x74, 0x49, 0x64, 0x1a, 0x0f, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x73,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x5a, 0x0a, 0x1f, 0x69, 0x6f, 0x2e, 0x63,
	0x72, 0x64, 0x73, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x6c, 0x65, 0x74, 0x73, 0x42, 0x0d, 0x44, 0x72, 0x6f,
	0x70, 0x6c, 0x65, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x26, 0x6d, 0x69,
	0x7a, 0x61, 0x72, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x64, 0x73, 0x2d, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x72, 0x6f, 0x70,
	0x6c, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_droplets_droplets_proto_rawDescOnce sync.Once
	file_droplets_droplets_proto_rawDescData = file_droplets_droplets_proto_rawDesc
)

func file_droplets_droplets_proto_rawDescGZIP() []byte {
	file_droplets_droplets_proto_rawDescOnce.Do(func() {
		file_droplets_droplets_proto_rawDescData = protoimpl.X.CompressGZIP(file_droplets_droplets_proto_rawDescData)
	})
	return file_droplets_droplets_proto_rawDescData
}

var file_droplets_droplets_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_droplets_droplets_proto_goTypes = []interface{}{
	(*Droplet)(nil),          // 0: droplets.Droplet
	(*DropletId)(nil),        // 1: droplets.DropletId
	(*Empty)(nil),            // 2: droplets.Empty
	(*DropletsResponse)(nil), // 3: droplets.DropletsResponse
}
var file_droplets_droplets_proto_depIdxs = []int32{
	0, // 0: droplets.DropletsService.CreateDroplet:input_type -> droplets.Droplet
	0, // 1: droplets.DropletsService.UpdateDroplet:input_type -> droplets.Droplet
	1, // 2: droplets.DropletsService.ReadDroplet:input_type -> droplets.DropletId
	1, // 3: droplets.DropletsService.DeleteDroplet:input_type -> droplets.DropletId
	1, // 4: droplets.DropletsService.ResumeDroplet:input_type -> droplets.DropletId
	2, // 5: droplets.DropletsService.CreateDroplet:output_type -> droplets.Empty
	2, // 6: droplets.DropletsService.UpdateDroplet:output_type -> droplets.Empty
	3, // 7: droplets.DropletsService.ReadDroplet:output_type -> droplets.DropletsResponse
	2, // 8: droplets.DropletsService.DeleteDroplet:output_type -> droplets.Empty
	2, // 9: droplets.DropletsService.ResumeDroplet:output_type -> droplets.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_droplets_droplets_proto_init() }
func file_droplets_droplets_proto_init() {
	if File_droplets_droplets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_droplets_droplets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Droplet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_droplets_droplets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropletId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_droplets_droplets_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_droplets_droplets_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropletsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_droplets_droplets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_droplets_droplets_proto_goTypes,
		DependencyIndexes: file_droplets_droplets_proto_depIdxs,
		MessageInfos:      file_droplets_droplets_proto_msgTypes,
	}.Build()
	File_droplets_droplets_proto = out.File
	file_droplets_droplets_proto_rawDesc = nil
	file_droplets_droplets_proto_goTypes = nil
	file_droplets_droplets_proto_depIdxs = nil
}
