# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

# Departing from the implicit _user.c scheme
USER_TARGETS := xdp_user_monitoring_prog

LIBBPF_DIR = ../../extern/libbpf/src/
# COMMON_DIR = ../common/

# include $(COMMON_DIR)/common.mk