@startuml

skinparam monochrome true
autonumber
database API_Server
collections VPC_Operator
collections Divider_Operator
collections Bouncer_Operator
collections Droplet_Operator

==VPC Created==
rnote over API_Server: ==VPC Status: Init
VPC_Operator --> API_Server: Sees VPC Status: Init
VPC_Operator -> API_Server: Creates a Divider Object
rnote over API_Server: ==Divider Status: Init
Divider_Operator --> API_Server: Sees Divider Status Init
Divider_Operator --> Droplet_Operator: Place Divider
Droplet_Operator -> Droplet_Operator: Places Divider on a Droplet
Droplet_Operator -> Bouncer_Operator: On Divider Placed
group For All Bouncers
Bouncer_Operator -> Bouncer_Operator: Updates  Bouncer with Divider info (No Bouncers)
Bouncer_Operator -> Bouncer_Operator: Updates Divider with Bouncer info (No Bouncers)
end
Bouncer_Operator -> API_Server: Updates status to Provisioned
rnote over API_Server: ==Divider Status: Provisioned
Divider_Operator --> API_Server: Sees status Provisioned
Divider_Operator -> Divider_Operator: Update cache
VPC_Operator -> API_Server : Updates VPC Status to Provisioned
rnote over API_Server: ==VPC Status: Provisioned
VPC_Operator --> API_Server: Sees VPC status Provisioned
VPC_Operator -> VPC_Operator: Update cache
==VPC Ready==

@enduml
