/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	vpcsv1 "mizar.futurewei.com/crds-operators/vpcs/v1"
	versioned "mizar.futurewei.com/crds-operators/vpcs/v1/apis/clientset/versioned"
	internalinterfaces "mizar.futurewei.com/crds-operators/vpcs/v1/apis/informers/externalversions/internalinterfaces"
	v1 "mizar.futurewei.com/crds-operators/vpcs/v1/apis/listers/vpcs/v1"
)

// TestResourceInformer provides access to a shared informer and lister for
// TestResources.
type TestResourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.TestResourceLister
}

type testResourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTestResourceInformer constructs a new informer for TestResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTestResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTestResourceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTestResourceInformer constructs a new informer for TestResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTestResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MizarV1().TestResources(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MizarV1().TestResources(namespace).Watch(options)
			},
		},
		&vpcsv1.TestResource{},
		resyncPeriod,
		indexers,
	)
}

func (f *testResourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTestResourceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *testResourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vpcsv1.TestResource{}, f.defaultInformer)
}

func (f *testResourceInformer) Lister() v1.TestResourceLister {
	return v1.NewTestResourceLister(f.Informer().GetIndexer())
}
