/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	vpcsv1 "mizar.futurewei.com/crds-operators/vpcs/v1"
)

// FakeTestResources implements TestResourceInterface
type FakeTestResources struct {
	Fake *FakeMizarV1
	ns   string
}

var testresourcesResource = schema.GroupVersionResource{Group: "mizar.futurewei.com", Version: "v1", Resource: "testresources"}

var testresourcesKind = schema.GroupVersionKind{Group: "mizar.futurewei.com", Version: "v1", Kind: "TestResource"}

// Get takes name of the testResource, and returns the corresponding testResource object, and an error if there is any.
func (c *FakeTestResources) Get(name string, options v1.GetOptions) (result *vpcsv1.TestResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(testresourcesResource, c.ns, name), &vpcsv1.TestResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*vpcsv1.TestResource), err
}

// List takes label and field selectors, and returns the list of TestResources that match those selectors.
func (c *FakeTestResources) List(opts v1.ListOptions) (result *vpcsv1.TestResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(testresourcesResource, testresourcesKind, c.ns, opts), &vpcsv1.TestResourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &vpcsv1.TestResourceList{ListMeta: obj.(*vpcsv1.TestResourceList).ListMeta}
	for _, item := range obj.(*vpcsv1.TestResourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested testResources.
func (c *FakeTestResources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(testresourcesResource, c.ns, opts))

}

// Create takes the representation of a testResource and creates it.  Returns the server's representation of the testResource, and an error, if there is any.
func (c *FakeTestResources) Create(testResource *vpcsv1.TestResource) (result *vpcsv1.TestResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(testresourcesResource, c.ns, testResource), &vpcsv1.TestResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*vpcsv1.TestResource), err
}

// Update takes the representation of a testResource and updates it. Returns the server's representation of the testResource, and an error, if there is any.
func (c *FakeTestResources) Update(testResource *vpcsv1.TestResource) (result *vpcsv1.TestResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(testresourcesResource, c.ns, testResource), &vpcsv1.TestResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*vpcsv1.TestResource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTestResources) UpdateStatus(testResource *vpcsv1.TestResource) (*vpcsv1.TestResource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(testresourcesResource, "status", c.ns, testResource), &vpcsv1.TestResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*vpcsv1.TestResource), err
}

// Delete takes name of the testResource and deletes it. Returns an error if one occurs.
func (c *FakeTestResources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(testresourcesResource, c.ns, name), &vpcsv1.TestResource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTestResources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(testresourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &vpcsv1.TestResourceList{})
	return err
}

// Patch applies the patch and returns the patched testResource.
func (c *FakeTestResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *vpcsv1.TestResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(testresourcesResource, c.ns, name, pt, data, subresources...), &vpcsv1.TestResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*vpcsv1.TestResource), err
}
