@startuml
autonumber
participant "EP_A at Host A" as a
participant "Old host of b" as old
participant "New host of b" as b
participant "Transit Switch" as S
a -> old: **direct-path bit** + Packet-1 to b
old -> a: **RTS with critical bit** + Packet-1 to b
a -> a: //invalidate endpoint_host_cache//
a -> S: **RTS Opt (a @ Host A)** + Packet-1 to b
S -> b: **RTS Opt (a @ Host A)** + Packet-1 to b
b -> b: //update endpoint_host_cache//
b -> a: **direct-path bit** + Packet-2 to a
a -> b: **direct-path bit** + Packet-3 to b
@enduml