@startuml

skinparam monochrome true

actor Client
collections Dividers
database Divider_Operator
collections Networks
database Network_Operator
collections Bouncers
database Bouncer_Operator
collections Endpoints
database Endpoints_Operator
collections Droplets
database Droplet_Operator

Client -> Networks: Client creates a Bouncer
Networks -> Bouncers: Creates a Bouncer Object
rnote over Bouncers: ==Init
Droplet_Operator --> Bouncers: Sees status Init
Droplet_Operator -> Droplets: Places Bouncer on Droplet
Droplet_Operator -> Bouncers: Updates status to Placed
rnote over Bouncers: ==Placed
Endpoints_Operator --> Bouncers: Sees status Placed
Endpoints_Operator -> Bouncers: Update new Bouncer with all endpoints (No Endpoint)
Endpoints_Operator -> Bouncers: Update status to EndpointReady
rnote over Bouncers: ==EndpointReady
Divider_Operator --> Bouncers: Sees status EndpointReady
Divider_Operator -> Bouncers: Update new Bouncer with all Dividers
Divider_Operator -> Dividers: Update all Dividers with new Bouncer
Divider_Operator -> Bouncers: Updates status to Provisioned
rnote over Bouncers: ==Provisioned
Bouncer_Operator --> Bouncers: Sees status provisioned
Bouncer_Operator -> Bouncer_Operator: Updates cache
Endpoints_Operator --> Bouncers: Sees status provisioned
Endpoints_Operator -> Endpoints: Updates all Endpoints with new Bouncer

@enduml
