@startuml

skinparam monochrome true
autonumber

database API_Server
collections Divider_Operator
collections Network_Operator
collections Bouncer_Operator
collections Endpoints_Operator
collections Droplet_Operator

==Network Created==
rnote over API_Server: ==Network Status: Init
Network_Operator --> API_Server: Sees status Init
Network_Operator -> API_Server: Create a Bouncer
rnote over API_Server: ==Bouncer Status Init
Droplet_Operator --> API_Server: Sees status Init
Droplet_Operator -> Droplet_Operator: Places Bouncer on Droplet
Droplet_Operator -> Endpoints_Operator: On Bouncer-Placed
group For All Endpoints
Endpoints_Operator -> Endpoints_Operator: Update new Bouncer with all endpoints (No Endpoints)
Endpoints_Operator -> Endpoints_Operator: Updates Endpoint with new Bouncer (No Endpoints)
end
Endpoints_Operator -> Divider_Operator: On Bouncer-EndpointReady
group For All Dividers
Divider_Operator -> Divider_Operator: Update new Bouncer with Divider
Divider_Operator -> Divider_Operator: Update Divider with new Bouncer
end
Divider_Operator -> API_Server: Updates status to Provisioned
rnote over API_Server: == Bouncer Status: Provisioned
Bouncer_Operator --> API_Server: Sees status provisioned
Bouncer_Operator -> Bouncer_Operator: Updates cache
Network_Operator -> API_Server: Updates Network status to provisioned
rnote over API_Server: == Network Status: Provisioned
Network_Operator --> API_Server: Sees Network status Provisioned
Network_Operator -> Network_Operator: Update cache
==Network Ready==
@enduml
