@startuml

skinparam monochrome true

actor Client
database CNI_Service
collections Networks
database Network_Operator
collections Bouncers
database Bouncer_Operator
collections Endpoints
database Endpoints_Operator
collections Droplets
database Droplet_Operator


Client -> CNI_Service: Client Creates an Endpoint
CNI_Service -> Endpoints: Initializes Endpoint (Allocates, veth-pair, netns, etc)
CNI_Service -> Droplets: Assigns Endpoint to Droplet
CNI_Service -> Endpoints: Sets status to Init
rnote over Endpoints: ==Init
Network_Operator --> Endpoints: Sees status Init
Network_Operator -> Endpoints: Allocates IP, Gw, etc.
Network_Operator -> Endpoints: Sets status to Alloc
rnote over Endpoints: ==Alloc
Bouncer_Operator --> Endpoints: Sees status Alloc
Bouncer_Operator -> Bouncers: Updates all Bouncers with new Endpoint
Bouncer_Operator -> Endpoints: Updates Endpoint with all Bouncers
Bouncer_Operator -> Endpoints: Updates status to Provisioned
rnote over Endpoints: ==Provisioned


@enduml
