@startuml

skinparam monochrome true
autonumber

database API_Server
collections CNI_Service
collections Network_Operator
collections Bouncer_Operator
collections Endpoints_Operator
collections Droplet_Operator

==Endpoint Created==
rnote over API_Server: == Endpoint Status: Init
Network_Operator --> API_Server: Sees Endpoint status Init
Network_Operator -> Network_Operator: Allocates IP, Gw, etc.
Network_Operator -> Bouncer_Operator: On Endpoint-Alloc
group For All Bouncers
Bouncer_Operator -> Bouncer_Operator: Updates Bouncer with new Endpoint
Bouncer_Operator -> Bouncer_Operator: Updates Endpoint with Bouncer
end
Bouncer_Operator -> CNI_Service: On Endpoint-Provisioned
CNI_Service -> CNI_Service: Write to CNI file.
Bouncer_Operator -> API_Server: Updates status to Provisioned
rnote over API_Server: ==Endpoint Status: Provisioned
Endpoints_Operator --> API_Server: Sees Endpoint status Provisioned
Endpoints_Operator --> Endpoints_Operator: Update cache
==Endpoint Ready==
@enduml
