@startuml

skinparam monochrome true

database API_Server
collections Divider_Operator
collections Network_Operator
collections Bouncer_Operator
collections Endpoints_Operator
collections Droplet_Operator

API_Server -> Network_Operator: Create a Network
Network_Operator --> API_Server: Creates a Network Object
rnote over API_Server: ==Network Status: Init
Network_Operator --> API_Server: Sees status Init
Network_Operator -> Bouncer_Operator: Create a Bouncer
Bouncer_Operator -> API_Server: Creates a Bouncer Object
rnote over API_Server: ==Bouncer Status Init
Droplet_Operator --> API_Server: Sees status Init
Droplet_Operator -> Droplet_Operator: Places Bouncer on Droplet

Droplet_Operator -> Endpoints_Operator: Bouncer Placed
Endpoints_Operator -> Endpoints_Operator: Update new Bouncer with all endpoints (No Endpoint)
Endpoints_Operator -> Endpoints_Operator: Update status to EndpointReady
Endpoints_Operator -> Divider_Operator: Bouncers are EndpointReady
Divider_Operator -> Divider_Operator: Update new Bouncer with all Dividers
Divider_Operator -> Divider_Operator: Update all Dividers with new Bouncer
Divider_Operator -> API_Server: Updates status to Provisioned
rnote over API_Server: == Bouncer Status: Provisioned

Bouncer_Operator --> API_Server: Sees status provisioned
Bouncer_Operator -> Bouncer_Operator: Updates cache
Endpoints_Operator --> API_Server: Sees Bouncer Status provisioned
Endpoints_Operator -> Endpoints_Operator: Updates all Endpoints with new Bouncer
Network_Operator --> API_Server: Sees Bouncer status provisioned
Network_Operator -> API_Server: Updates Network status to provisioned
rnote over API_Server: == Network Status: Provisioned
@enduml
